### ISSUE TITLE
Support PyStrings

### ISSUE THREAD

**Issue by kalupa** [codegram/gherkin-ruby#20]
Multi-line strings work great in the native gherkin but gherkin-ruby doesn't seem to be a big fan.

``````
/Users/paul/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/1.9.1/racc/parser.rb:351:in `on_error':  (Racc::ParseError)
parse error on value "\"\"\"" (TEXT)
    from (eval):3:in `_racc_do_parse_c'
    from (eval):3:in `do_parse'
    from /Users/paul/.rvm/gems/ruby-1.9.3-p194/gems/gherkin-ruby-0.2.1/lib/gherkin/parser/lexer.rb:31:in `scan_str'
    from gherkin.y:107:in `parse'
    from /Users/paul/.rvm/gems/ruby-1.9.3-p194/gems/gherkin-ruby-0.2.1/lib/gherkin.rb:8:in `parse'
    from /Users/paul/.rvm/gems/ruby-1.9.3-p194/gems/spinach-0.5.2/lib/spinach/parser.rb:39:in `parse'
    from /Users/paul/.rvm/gems/ruby-1.9.3-p194/gems/spinach-0.5.2/lib/spinach/runner.rb:66:in `block in run'
    from /Users/paul/.rvm/gems/ruby-1.9.3-p194/gems/spinach-0.5.2/lib/spinach/runner.rb:63:in `each'
    from /Users/paul/.rvm/gems/ruby-1.9.3-p194/gems/spinach-0.5.2/lib/spinach/runner.rb:63:in `run'
    from /Users/paul/.rvm/gems/ruby-1.9.3-p194/gems/spinach-0.5.2/lib/spinach/cli.rb:23:in `run'
    from /Users/paul/.rvm/gems/ruby-1.9.3-p194/gems/spinach-0.5.2/bin/spinach:16:in `<top (required)>'
    from /Users/paul/.rvm/gems/ruby-1.9.3-p194/bin/spinach:19:in `load'
    from /Users/paul/.rvm/gems/ruby-1.9.3-p194/bin/spinach:19:in `<main>'
    from /Users/paul/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/paul/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'```
``````

**Comment by txus** [comment]
Closing in favor of #24.
